-- Seed content for contentforge.
INSERT OR REPLACE INTO articles
        (id,tenant_id,url_sha256,source_id,source_url,title,slug,category,badge,read_time,seo_title,description,hero_angle,highlights_json,content,cta_text,hero_media_id,is_archived,created_at,updated_at)
       VALUES (
        'why-every-canvassing-team-needs-a-dedicated-canvass-app-2026','usr_admin_demo','35a01ad8f681f2dab87badf80b44cbf963d2bada937124671faf040bd1abfed8',NULL,'urn:contentforge-seed:why-every-canvassing-team-needs-a-dedicated-canvass-app-2026','Why Every Canvassing Team Needs a Dedicated Canvass App in 2026','/blog/why-every-canvassing-team-needs-a-dedicated-canvass-app-2026',
        'Guides','Article','9 min read','Why Every Canvassing Team Needs a Dedicated Canvass App in 2026 | Acme','A sales rep knocks on doors all day, writes notes in a notebook, clicks a few photos, maybe sends updates on WhatsApp, and promises to enter everything later. By the time the day ends, half the leads are incomplete.',
        'The Silent Revenue Killer Hiding in Your Team''s Notebooks','["Paper-based tracking quietly destroys conversion and field rep accountability.","A dedicated canvass app dramatically improves ROI, accuracy, and overall team performance.","Small businesses benefit faster because even small efficiency gains translate quickly into higher conversions.","The right canvass app reduces manual work and fits naturally into how door-to-door sales actually happen.","When data replaces chaos, daily activity transforms into clear, actionable insights."]','Paper-based tracking still exists in direct sales because it feels simple. No login, no setup, no learning curve. But what it really does is quietly destroy your revenue potential. In 2026, this gap is no longer affordable.

A modern canvass app like Acme integrates lead management, pipeline tracking, territory management, and team messaging into one efficient screen, so reps know exactly what to do next, and managers can make informed decisions using real data.',NULL,NULL,0,'2026-05-22T09:50:48.142Z','2026-05-22T09:50:48.142Z');
INSERT OR REPLACE INTO articles
        (id,tenant_id,url_sha256,source_id,source_url,title,slug,category,badge,read_time,seo_title,description,hero_angle,highlights_json,content,cta_text,hero_media_id,is_archived,created_at,updated_at)
       VALUES (
        'door-to-door-salesperson-skills-every-rep-needs','usr_admin_demo','0ad88d8e9989124244ed758419460acc0d689a75cb36d0857a64ec18aebbf2d6',NULL,'urn:contentforge-seed:door-to-door-salesperson-skills-every-rep-needs','Door-to-Door Salesperson: Skills Every Rep Needs to Master','/blog/door-to-door-salesperson-skills-every-rep-needs',
        'Guides','Article','7 min read','Door-to-Door Salesperson: Skills Every Rep Needs to Master | Acme','Door-to-door sales reps often get labeled as ''pushy'' or ''intrusive'', leading to split-second rejections. Learn the five crucial skills that turn standard interactions into signed deals.',
        'The Truth Nobody Tells You About D2D Sales','["Communication skills: mastering the first 10 seconds with confident non-verbal and verbal interest hooks.","Active listening and empathy: reading body language and improvising on the go instead of repeating a static script.","Product knowledge: framing your roofing/solar offering as a problem solver instead of just pitching features.","Objection handling: using the LAER Model (Listen, Acknowledge, Explore, Respond) to create value-driven proof.","Follow-up systems: executing the 3Fs (Follow Up, Follow Through, Follow Back) where 80% of sales are typically lost."]','With an average conversion rate of just 2-5%, rejection is a daily reality. But direct sales in the US generate $34.7B in retail revenue. The real edge comes from mastering those face-to-face skills that build localized trust and close high-ticket roofing files.',NULL,NULL,0,'2026-05-22T09:50:48.142Z','2026-05-22T09:50:48.142Z');
INSERT OR REPLACE INTO articles
        (id,tenant_id,url_sha256,source_id,source_url,title,slug,category,badge,read_time,seo_title,description,hero_angle,highlights_json,content,cta_text,hero_media_id,is_archived,created_at,updated_at)
       VALUES (
        'ultimate-guide-d2d-experts-skills-training-tools-2026','usr_admin_demo','b85bb2446d1b62925ffbf3f7237858f1392fed7cadff8ea52f375ffe3ff00a4b',NULL,'urn:contentforge-seed:ultimate-guide-d2d-experts-skills-training-tools-2026','The Ultimate Guide to Becoming D2D Experts: Skills, Training & Tools (2026)','/blog/ultimate-guide-d2d-experts-skills-training-tools-2026',
        'Guides','Guide','6 min read','The Ultimate Guide to Becoming D2D Experts | Acme','The complete playbook for D2D sales mastery. How modern field reps combine route analytics, cloud tracking, storm layers, and smart commissions.',
        'The Complete Playbook for D2D Sales Mastery and Growth','["Field sales have transitioned from raw grit to structured analytical operations.","Pattern-based engagement has replaced script-based approaches to boost micro-conversions.","Reps are scaling quickly by playing to industry specialization (roof claims, solar ROI).","Route optimization removes dead miles and scales active hours per day.","Acme unifies commissions, storm overlays, and team maps in a single mobile workspace."]','Becoming a D2D expert is about predictive precision. The best reps treat their territory like a hyper-local campaign, analyzing door-to-close ratios and timing to capture high-density solar and roofing potential.',NULL,NULL,0,'2026-05-22T09:50:48.142Z','2026-05-22T09:50:48.142Z');
INSERT OR REPLACE INTO articles
        (id,tenant_id,url_sha256,source_id,source_url,title,slug,category,badge,read_time,seo_title,description,hero_angle,highlights_json,content,cta_text,hero_media_id,is_archived,created_at,updated_at)
       VALUES (
        'hiring-training-door-knockers-tips-for-success','usr_admin_demo','59b5e4cf93f2b1ceb9e7d5a35593382e88057860a96bc341b4d369519bc61c8f',NULL,'urn:contentforge-seed:hiring-training-door-knockers-tips-for-success','Hiring & Training Door Knockers: Tips for Success','/blog/hiring-training-door-knockers-tips-for-success',
        'Guides','Article','4 min read','Hiring & Training Door Knockers: Tips for Success | Acme','Average annual sales turnover sits at 35%. Learn how to build an unstoppable team by using mobile onboarding, gamification, and stress reduction.',
        'The Revolving Door Problem -- And How to Fix It','["Identify resilience and adaptability upfront during candidate interviews.","Implement a mobile-first onboarding track to put training resources directly in reps'' pockets.","Drive engagement using gamified leaderboards, point systems, and badge rewards.","Provide real-time coaching feedback and microlearning based on field analytics.","Reduce stress and early burnout using route optimization and clear commission visualizers."]','High rep attrition quietly drains company profits. By shifting from printed manuals to interactive, mobile-guided gamified experiences, you can shorten ramp-up times and motivate a new generation of field team members.',NULL,NULL,0,'2026-05-22T09:50:48.142Z','2026-05-22T09:50:48.142Z');
INSERT OR REPLACE INTO articles
        (id,tenant_id,url_sha256,source_id,source_url,title,slug,category,badge,read_time,seo_title,description,hero_angle,highlights_json,content,cta_text,hero_media_id,is_archived,created_at,updated_at)
       VALUES (
        'door-to-door-vs-digital-leads-where-to-invest-marketing-budget','usr_admin_demo','8774937af6aab1b726fa836ff85550f7b9834ee02ea18b6a3227e6897b0c3ff6',NULL,'urn:contentforge-seed:door-to-door-vs-digital-leads-where-to-invest-marketing-budget','Door-to-Door vs Digital Leads: Where to Invest','/blog/door-to-door-vs-digital-leads-where-to-invest-marketing-budget',
        'Guides','Article','4 min read','Door-to-Door vs Digital Leads: Where to Invest | Acme','Digital leads can cost up to $82 in home services with high Google CPCs. Discover the ROI comparison and how to run a high-converting hybrid strategy.',
        'The $82 Question That Could Define Your Next Quarter','["Top-performing contractors combine hyper-local field trust with automated digital follow-ups.","Digital CPCs are surging, resulting in high customer acquisition costs (CAC) for competitive counties.","D2D delivers stable, predictable trust loops ideal for localized storm damage campaigns.","A hybrid model uses D2D for initial relationship building and digital ads/emails for community nurturing."]','You don''t have to choose between field canvassing and digital leads. Acme acts as the connector, letting you map field-captured intelligence into nurturing channels to drive customer referrals.',NULL,NULL,0,'2026-05-22T09:50:48.142Z','2026-05-22T09:50:48.142Z');
INSERT OR REPLACE INTO articles
        (id,tenant_id,url_sha256,source_id,source_url,title,slug,category,badge,read_time,seo_title,description,hero_angle,highlights_json,content,cta_text,hero_media_id,is_archived,created_at,updated_at)
       VALUES (
        'gamification-techniques-motivate-sales-reps','usr_admin_demo','7b80c9a59d8ac081a3af5ead76fb24437ca10cdf841713021ed67e013ad26a99',NULL,'urn:contentforge-seed:gamification-techniques-motivate-sales-reps','Gamification Techniques to Motivate Your Sales Reps','/blog/gamification-techniques-motivate-sales-reps',
        'Guides','Article','4 min read','Gamification Techniques to Motivate Your Sales Reps | Acme','Unravel the science of sales behavior gamification. Turn routine door-knocking into structured challenges that bolster morale and boost pipeline activity.',
        'Why Your Sales Team Is Losing Engagement (And How to Fix It)','["Quotas feel distant when they aren''t tied to daily metrics like doors knocked or pitches done.","Moral rises when feedback operates on immediate recognition loops instead of retroactive monthly reviews.","Reps perform better when friendly competition is displayed via live, mobile-ready team scoreboards.","Gamification on Acme integrates points, custom badges, and squad battles seamlessly into CRM habits."]','Field sales can be lonely. Gamification builds virtual fire around daily actions, turning CRM compliance and follow-ups into points, ranks, and badges that build real momentum across the field structure.',NULL,NULL,0,'2026-05-22T09:50:48.142Z','2026-05-22T09:50:48.142Z');
INSERT OR REPLACE INTO articles
        (id,tenant_id,url_sha256,source_id,source_url,title,slug,category,badge,read_time,seo_title,description,hero_angle,highlights_json,content,cta_text,hero_media_id,is_archived,created_at,updated_at)
       VALUES (
        '8-common-pitfalls-door-to-door-campaigns-how-to-avoid','usr_admin_demo','5b116ea60701477e9881e8cb8e6a70233868f68a0ba4e79a0ceb3385c55e8b1f',NULL,'urn:contentforge-seed:8-common-pitfalls-door-to-door-campaigns-how-to-avoid','8 Common Pitfalls in Door-to-Door Campaigns','/blog/8-common-pitfalls-door-to-door-campaigns-how-to-avoid',
        'Guides','Article','4 min read','8 Common Pitfalls in Door-to-Door Campaigns | Acme','Avoidable field mistakes like bad timing, rigid scripts, messy lists, and missing follow-ups can waste 40% of your canvassing efforts.',
        'Your Field Manual for Turning Every Knock Into Results','["Knocking at optimal contact times (evenings and weekends) instead of empty midday slots.","Swapping robotic scripts for flexible bullet points that encourage personal authenticity.","Eliminating duplicate work or overlapping territories with digital geo-locking.","Logging visit states instantly using mobile apps before memory or context is lost."]','Most canvassing teams don''t fail due to bad product; they fail due to operational friction. Building a responsive, data-driven workflow protects rep morale and converts more opportunities.',NULL,NULL,0,'2026-05-22T09:50:48.142Z','2026-05-22T09:50:48.142Z');
INSERT OR REPLACE INTO articles
        (id,tenant_id,url_sha256,source_id,source_url,title,slug,category,badge,read_time,seo_title,description,hero_angle,highlights_json,content,cta_text,hero_media_id,is_archived,created_at,updated_at)
       VALUES (
        'why-d2d-sales-outperform-digital-channels-2025','usr_admin_demo','e36c9240535b68ee69f46269a01ead62347b70a0e42885baaa7f8cac69cb87a1',NULL,'urn:contentforge-seed:why-d2d-sales-outperform-digital-channels-2025','Why D2D Sales Still Outperform Digital Channels in 2025','/blog/why-d2d-sales-outperform-digital-channels-2025',
        'Guides','Article','4 min read','Why D2D Sales Still Outperform Digital Channels in 2025 | Acme','In an era of search overview shrinkages and digital ad blockers, face-to-face rapport builds unbeatable credibility for high-ticket roofing and solar deals.',
        'The Human Connection Beats the Algorithm -- Every Time','["Ad click-through rates are facing severe drops due to digital fatigue and AI search results.","A customized in-person presentation handles objections on the spot with high local trust.","Geo-targeted field efforts tie directly to local demographics without reliance on changing third-party cookies.","Acme bridges the gap by linking offline doorstep trust directly into dynamic estimation tools."]','Every brand is competing for clicks, but the porch interaction remains the most direct way to establish authority. In home services, localized, face-to-face engagement continues to drive the highest close rates.',NULL,NULL,0,'2026-05-22T09:50:48.142Z','2026-05-22T09:50:48.142Z');
INSERT OR REPLACE INTO articles
        (id,tenant_id,url_sha256,source_id,source_url,title,slug,category,badge,read_time,seo_title,description,hero_angle,highlights_json,content,cta_text,hero_media_id,is_archived,created_at,updated_at)
       VALUES (
        'how-acme-integrates-with-your-sales-workflow','usr_admin_demo','75955b238f8cd7cd4ba2e0fba8333294f2de93590baf2c82e3344d56e78eb17e',NULL,'urn:contentforge-seed:how-acme-integrates-with-your-sales-workflow','How Acme Integrates With Your Sales Workflow','/blog/how-acme-integrates-with-your-sales-workflow',
        'Guides','Article','4 min read','How Acme Integrates With Your Sales Workflow | Acme','Silos and manual double entry drain revenue. Learn how same-day setup, automated reminders, and HailTrace storm tracking keep your pipeline moving.',
        'Stop Hustling Harder. Start Winning Smarter.','["Connect isolated systems to eliminate lead state friction and manual typos.","Ensure live offline sync so reps can work rural storm zones without connection gaps.","Integrate HailTrace data directly into the canvasser map to target damaged roof addresses instantly.","Automate CRM notifications to inside sales teams the minute a pitch lands in the field."]','Your roofing command center has to work at the speed of the storm. Acme connects the initial knock, active route tracking, adjuster report, contract signature, and production timeline to turn field activity into revenue.',NULL,NULL,0,'2026-05-22T09:50:48.142Z','2026-05-22T09:50:48.142Z');
INSERT OR REPLACE INTO articles
        (id,tenant_id,url_sha256,source_id,source_url,title,slug,category,badge,read_time,seo_title,description,hero_angle,highlights_json,content,cta_text,hero_media_id,is_archived,created_at,updated_at)
       VALUES (
        'acme-review-beyond-door-to-door-tracking','usr_admin_demo','40d8a6b608064c3817df4c9861b769f165c2c1df8dc33c551f4d374eab545e02',NULL,'urn:contentforge-seed:acme-review-beyond-door-to-door-tracking','Acme Review: Beyond Just Door-to-Door Tracking','/blog/acme-review-beyond-door-to-door-tracking',
        'Reviews','Review','4 min read','Acme Review: Beyond Just Door-to-Door Tracking | Acme','An in-depth review of Acme''s robust operations: territory controls, team dashboards, visual commission calculators, and mobile offline maps.',
        'More Than a Canvassing App -- An Operating System for Field Sales','["Replace scattered spreadsheets with a centralized, collaborative team workspace.","Drive rep retention with visual, transparent, smart commission milestone calculations.","Gain precise operational visibility into rep metrics (visit outcomes, routing, appointments completed).","Attach custom forms, inspection media, and property roof measurements inside a single lead file."]','Many field tools track coordinates, but Acme operates as a true field OS. It gives contractors the tools to control the storm canvassing, estimate delivery, contract signatures, and payouts effortlessly.',NULL,NULL,0,'2026-05-22T09:50:48.142Z','2026-05-22T09:50:48.142Z');
INSERT OR REPLACE INTO articles
        (id,tenant_id,url_sha256,source_id,source_url,title,slug,category,badge,read_time,seo_title,description,hero_angle,highlights_json,content,cta_text,hero_media_id,is_archived,created_at,updated_at)
       VALUES (
        '5-features-acme-ideal-solar-roofing-canvassers','usr_admin_demo','a7516e85f960f410769f4b2cd289c15c623bbd1795cdffd45f094e22d4464b40',NULL,'urn:contentforge-seed:5-features-acme-ideal-solar-roofing-canvassers','5 Features That Make Acme the Definitive Choice','/blog/5-features-acme-ideal-solar-roofing-canvassers',
        'Guides','Article','4 min read','5 Features Ready for Solar & Roofing Canvassers | Acme','Explore the core roofing features: smart multi-pin overlays, live tracking, instant lead assignment, offline routing, and customized pitch flow.',
        'Built for the Field, Not the Boardroom','["Smart Territory & Pin Drop: eliminate double knocks with color-coded, labeled result pins.","GPS tracking & squad metrics keep operations transparent while boosting rep coaching.","Instant lead capture sync gets warm homeowner files straight into inside sales queues.","Full offline functionality works in dead spots and updates automatically when reconnected."]','When you''re out knocking in the Texas heat or freezing winds, you don''t need a bloated desktop CRM. Acme is optimized for extreme field usability, turning quick clicks into accurate data folders.',NULL,NULL,0,'2026-05-22T09:50:48.142Z','2026-05-22T09:50:48.142Z');
INSERT OR REPLACE INTO articles
        (id,tenant_id,url_sha256,source_id,source_url,title,slug,category,badge,read_time,seo_title,description,hero_angle,highlights_json,content,cta_text,hero_media_id,is_archived,created_at,updated_at)
       VALUES (
        'complete-guide-spotio-field-sales-engagement-platform','usr_admin_demo','934390fbb4ae00d32cbcab8d5de6871b78f5fa719fa832ef1f390670108bf75f',NULL,'urn:contentforge-seed:complete-guide-spotio-field-sales-engagement-platform','The Complete Guide to SPOTIO: Field Sales Engagement','/blog/complete-guide-spotio-field-sales-engagement-platform',
        'Reviews','Review','4 min read','The Complete Guide to SPOTIO | Acme Alternative','Analyze SPOTIO''s enterprise capabilities and see why growing roofing teams find Acme''s unified setup, storm layers, and commission tracker a better fit.',
        'Understanding SPOTIO -- And Why Acme Is the Smarter Choice','["SPOTIO suits massive enterprise layouts requiring complex corporate CRM setups.","The learning curve is high and setup features can feel bloated for nimble contractors.","Acme delivers focused, same-day onboarding, built-in storm response, and simpler UX.","Transparent flat-rate packages of Acme prevent the hidden overhead and custom quotes of SPOTIO."]','While enterprise databases serve a role, field teams need speed and simplicity. Acme focuses on high rep adoption by making map interactions, commission tracking, and reporting absolute priorities.',NULL,NULL,0,'2026-05-22T09:50:48.142Z','2026-05-22T09:50:48.142Z');
INSERT OR REPLACE INTO articles
        (id,tenant_id,url_sha256,source_id,source_url,title,slug,category,badge,read_time,seo_title,description,hero_angle,highlights_json,content,cta_text,hero_media_id,is_archived,created_at,updated_at)
       VALUES (
        'ultimate-guide-salesrabbit-door-to-door-sales-teams','usr_admin_demo','3aab87b35510ce365293c62dd3e2534e38f40debee06dcb465ce747a5e48d5b0',NULL,'urn:contentforge-seed:ultimate-guide-salesrabbit-door-to-door-sales-teams','The Ultimate Guide to SalesRabbit for D2D','/blog/ultimate-guide-salesrabbit-door-to-door-sales-teams',
        'Reviews','Review','4 min read','The Ultimate Guide to SalesRabbit for D2D Team | Alternative','Compare SalesRabbit''s features with Acme. Explore the benefits of built-in commission calculators, advanced gamification, same-day onboarding, and deep storm overlays.',
        'SalesRabbit: A Solid Start -- But Acme Is Where You Finish','["SalesRabbit is a widely known legacy tracking app, but lacks fully built-in commission engines.","Contractors report persistent mobile sync issues, disappearing pin status, and turf lockouts.","Acme solves adoption with a seamless app, same-day launch, and comprehensive offline buffers.","Get built-in storm weather features on Acme to plan claims response without costly add-on layers."]','Choosing the right platform is the difference between keeping your reps in the field or dealing with disconnected spreadsheets. Acme brings everything together under one hood without complicated add-on structures.',NULL,NULL,0,'2026-05-22T09:50:48.142Z','2026-05-22T09:50:48.142Z');
INSERT OR REPLACE INTO battlecards
        (id,tenant_id,source_id,category,objection,counter_wedge,discovery_questions_json,one_liner,metrics_json,competitor_domain,is_archived,created_at,updated_at)
       VALUES (
        'ai_sdr','usr_admin_demo',NULL,'lead_generation','Roof Flow AI has a 24/7 AI SDR that responds to leads in 60 seconds and books appointments.','Fast follow-up is excellent, but if your field operation is disconnected, you are just booking empty walkthroughs. Booking the inspection is not the finish line. Acme centers on the entire roof file: storm layers, damage analysis, measurements, instant reports, signatures, and team payouts. We ensure your reps turn those booked inspection slots into documented revenue.',
        '["After the AI books the inspection, what happens to the shingle photos, roof pitch numbers, and adjustor notes?","Do your field reps have to manually transfer client info into multiple separate reporting tools in their truck?"]','Roof Flow AI books the inspection appointment. Acme helps your team win everything after the storm.','[{"label":"Win-rate with reports","value":"+30%"},{"label":"Admin time saved","value":"4.5 hrs/week"}]',NULL,0,'2026-05-22T09:50:48.142Z','2026-05-22T09:50:48.142Z');
INSERT OR REPLACE INTO battlecards
        (id,tenant_id,source_id,category,objection,counter_wedge,discovery_questions_json,one_liner,metrics_json,competitor_domain,is_archived,created_at,updated_at)
       VALUES (
        'ads_autopilot','usr_admin_demo',NULL,'storm_response','They have referrals on autopilot and a built-in AI Facebook ad launcher.','Generic digital leads are getting more expensive. A single roofing lead can cost $82, and PPC ads face severe click exhaustion. Roofers don''t grow by throwing money at Google/Facebook algorithms. They grow by targeting storm zones. Acme combines live HailTrace storm metrics and interactive maps so you place your reps directly on streets with documented damage shingle details.',
        '["What is your actual customer acquisition cost (CAC) on digital Facebook ads currently?","How do your reps currently coordinate routes in a fresh storm district to prevent double knocks?"]','Search ads scale expensive views, but hyper-local storm intelligence secures high-margin roof contracts.','[{"label":"Cost-Per-Lead reduction","value":"-45%"},{"label":"Hail mapping accuracy","value":"100%"}]',NULL,0,'2026-05-22T09:50:48.142Z','2026-05-22T09:50:48.142Z');
INSERT OR REPLACE INTO battlecards
        (id,tenant_id,source_id,category,objection,counter_wedge,discovery_questions_json,one_liner,metrics_json,competitor_domain,is_archived,created_at,updated_at)
       VALUES (
        'onboarding_speed','usr_admin_demo',NULL,'onboarding','Roof Flow AI offers done-for-you options where they set up your settings entirely.','DFY sounds appealing, but waiting on support queues to change your commission structure, adjust report values, or onboard a new rookie is frustrating. Acme offers intuitive same-day onboarding and direct workflow controls. You are in complete control of your estimates, reports, and zones from minute one.',
        '["If you need to change your pricing list, add contract terms, or adjust a commission model today, how long do you have to wait on support?","Can your team roll out a fresh training course to new reps directly inside their mobile app?"]','Their system requires support setup; Acme offers same-day launch and complete operational agility.','[{"label":"Integration time","value":"< 2 hours"},{"label":"Ramp up window","value":"Under 1 day"}]',NULL,0,'2026-05-22T09:50:48.142Z','2026-05-22T09:50:48.142Z');
INSERT OR REPLACE INTO battlecards
        (id,tenant_id,source_id,category,objection,counter_wedge,discovery_questions_json,one_liner,metrics_json,competitor_domain,is_archived,created_at,updated_at)
       VALUES (
        'crm_pipeline','usr_admin_demo',NULL,'report_claim','We already have standard pipeline cards in our current CRM to organize jobs.','Standard CRMs treat customer records like flat contact folders. Acme replaces simple boxes with a dedicated roof file timeline. Built specifically for roofing contractors, it unifies shingle measurements, storm dates, adjuster reports, signed contracts, and commission states, making evidence adjuster-ready instantly.',
        '["Does your current CRM track roof parameters, wind direction, and adjuster packets natively on a single screen?","How do your reps check their current pending commission payouts on active active installations?"]','Older databases organize spreadsheets. Acme operates as a true field OS for your roofers.','[{"label":"Double-entry errors","value":"0"},{"label":"Average contract value","value":"+12%"}]',NULL,0,'2026-05-22T09:50:48.142Z','2026-05-22T09:50:48.142Z');
INSERT OR REPLACE INTO content_sources
        (id,tenant_id,kind,url,label,category,badge,is_active,fail_count,last_run_at,last_error,created_at,updated_at)
       VALUES (
        'src_acme_blog','usr_admin_demo','rss','https://blog.example.com/feed.xml','Acme Blog','Guides','Article',1,0,NULL,NULL,'2026-05-22T09:50:48.142Z','2026-05-22T09:50:48.142Z');
INSERT OR REPLACE INTO content_sources
        (id,tenant_id,kind,url,label,category,badge,is_active,fail_count,last_run_at,last_error,created_at,updated_at)
       VALUES (
        'src_reddit_roofing','usr_admin_demo','reddit','https://www.reddit.com/r/Roofing/.json','r/Roofing (hot)','Trends','Article',1,0,NULL,NULL,'2026-05-22T09:50:48.142Z','2026-05-22T09:50:48.142Z');
INSERT OR REPLACE INTO content_sources
        (id,tenant_id,kind,url,label,category,badge,is_active,fail_count,last_run_at,last_error,created_at,updated_at)
       VALUES (
        'src_reddit_insurance','usr_admin_demo','reddit','https://www.reddit.com/r/Insurance/.json','r/Insurance (hot)','Trends','Article',1,0,NULL,NULL,'2026-05-22T09:50:48.142Z','2026-05-22T09:50:48.142Z');
INSERT OR REPLACE INTO content_sources
        (id,tenant_id,kind,url,label,category,badge,is_active,fail_count,last_run_at,last_error,created_at,updated_at)
       VALUES (
        'src_google_news_roofing','usr_admin_demo','rss','https://news.google.com/rss/search?q=roofing+insurtech&hl=en-US&gl=US&ceid=US:en','Google News — Roofing Insurtech','News','Article',1,0,NULL,NULL,'2026-05-22T09:50:48.142Z','2026-05-22T09:50:48.142Z');
